spring.application.name=phase-2

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=pnpt123

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# =======================
# Kafka (docker expose 9092 ra máy)
# =======================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=task-events-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.acks=all

app.kafka.topic=task.events


# =======================
# MongoDB (docker expose 27017 ra máy)
# =======================
spring.data.mongodb.uri=mongodb://localhost:27017/app

spring.jpa.hibernate.ddl-auto=update